name: unit tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run Unit tests
      run: python3 -m unittest tests/test_scrapper.py